In [5]:
import numpy as np
import csv
#import pandas as pd
import sys
import time
import math


from collections import Counter
import statistics 


# ------------------------------- Ofline Recommender System----------------------

#   find dot Product betweeen a And B and return the result

def dot(A,B): 
    return (sum(int(a)*int(b) for a,b in zip(A,B)))

#  ------- FUnction For Cosine Similarity-----------

def cosine_similarity(A,B,dataset):
    a=dataset[A]
    b=dataset[B]
    return dot(a,b) / ( (dot(a,a) **.5) * (dot(b,b) ** .5) )

# -------- Function For Jaccard Similarity-------

def jaccard_repeats(list1, list2):
    result = 0
    result1 = 0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
           result = result +1
        if(list1[i]!='0' or list2[i]!='0'):
            result1 = result1 +1
    return  result/result1
# ----------- Function For Sigmoid Pearson Corelation ------------
def spcc_cosine_similarity(list1, list2):
    result = 0
    #print(list1)
    #print(list2)
    result1 = 0
    sum1=0
    sum2=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' ):
           sum1=sum1+int(list1[i])
           result = result +1
        if(list2[i]!='0'):
           sum2=sum2+int(list2[i])
           result1 = result1 +1
    min1=sum1/result
    min2=sum2/result1
    #print("Min Value of 1st List::",min1)
    #print("Min Value of 2nd List",min2)
    sum2=0
    div1=0
    div2=0
    result=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
            sum2=sum2 + (int(list1[i])-min1)*(int(list2[i])-min2)
            div1=div1 + (int(list1[i])-min1)**2
            div2=div2 + (int(list2[i])-min2)**2
            result =result +1
    #print("PCC=",sum2,"/sqrt(",div1*div2,")")
    #print("ddd::",div2)
    ans=sum2/(np.sqrt(div1*div2))
    ans=ans * sigmoid(result) * 1.135
    return ans

def sigmoid(x):
  return 1 / (1 + math.exp(-x/2))


# ------ Function For calcilate Msd Measure

def msd_repeats(list1, list2):
    result = 0
    #print(list2)
    sum2=0
    div1=0
    div2=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
            sum2=sum2 + (int(list1[i])- int(list2[i]))**2
            div2=div2 +1 
    #print("MSD=",sum2,"/(",div2,")")
    #print("ddd::",div2)
    ans=1-sum2/div2
    return ans
# -------------Function For Cpcc Measure-----------
def cpcc_repeats(list1, list2):
    result = 0
    r_med=3
    
   
    sum2=0
    div1=0
    div2=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
            sum2=sum2 + (int(list1[i])-r_med)*(int(list2[i])-r_med)
            div1=div1 + (int(list1[i])-r_med)**2
            div2=div2 + (int(list2[i])-r_med)**2
    #print("CPCC=",sum2,"/sqrt(",div1*div2,")")
    
    ans=sum2/(math.sqrt(div1*div2))
    return ans   

# -------------- Function For Pcc SImilarity Measure--------

def pcc_repeats(list1, list2):
    result = 0
    
    #print(list1)
    #print(list2)
    sum1=0
    sum2=0
    result1 = 0
    for i in range(0, len(list1)):
        if(list1[i]!='0' ):
           sum1=sum1+int(list1[i])
           result = result +1
        if(list2[i]!='0'):
           sum2=sum2+int(list2[i])
           result1 = result1 +1
    min1=sum1/result
    min2=sum2/result1
    #print("Min Value of 1st List::",min1)
    #print("Min Value of 2nd List",min2)
    sum2=0
    div1=0
    div2=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
            sum2=sum2 + (int(list1[i])-min1)*(int(list2[i])-min2)
        
            div1=div1 + (int(list1[i])-min1)**2
       
            div2=div2 + (int(list2[i])-min2)**2
    #print("ACOS=",sum2,"/sqrt(",div1*div2,")")
    
    ans=sum2/(np.sqrt(div1*div2))
    return ans

# -----------Function FOr Finding User Mean ----------

def user_mean(list1):
    result = 0
    count = 0
    print(list1)
    for i in range(0,len(list1)):
        if (list1[i]!='0'):
            result = result + int(list1[i])
            count = count+1
    return result/count


# ------------------- NHSM ---------------------

def nhsm_matrix_similarity(list1, list2):
    result = 0
    sum1=0
    #print(list1)
    #print(list2)
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
           sum1=sum1+int(list1[i])
           result = result +1
    min1=sum1/result
    prox=0
    sign=0
    sing = 0
    sum_pss=0
    for i in range(0, len(list1)):
        if(list1[i]!='0' and list2[i]!='0'):
            prox=prox+(1-(1/(1 + math.exp(-abs(int(list1[i])-int(list2[i]))))))
            sign = sign + (1/(1 + math.exp(-abs((int(list1[i])- 3)*(int(list2[i])-3)))))
            sing = sing + (1-(1/(1 + math.exp(-abs((int(list1[i])+int(list2[i]))/2-min1)))))
            pss= prox * sign * sing
            sum_pss=sum_pss+ pss
    jpss = jaccard_repeats(list1, list2) * sum_pss
    result = 0
    result1 = 0
    sum1 = sum2 =0
    for i in range(0, len(list1)):
        if(list1[i]!='0' ) :
            sum1=sum1+int(list1[i])
            result = result +1
        if( list2[i]!='0'):
            sum2=sum2+int(list2[i])
            result1 = result1 +1
        list3 = []
        for i in range(len(list1)):
            list3.append(int(list1[i]))
        list4 = []
        for i in range(len(list2)):
            list4.append(int(list2[i]))
    min1=sum1/result
    min2=sum2/result1
    std1=statistics.stdev(list3)
    std2=statistics.stdev(list4)
    upr=1-1/(1 + math.exp(-abs((min1-min2)*(std1-std2))))
    ans= jpss * upr
    return ans 

# ------------ Read Input File --------

with open( "Book1.csv") as csvfile:
    csvreader = csv.reader(csvfile)
    #next(csvreader, None)  # if 1st row is list then active
    dataset = list(csvreader)
    print(dataset)
total_users=5
total_item = 4

# ----- Declare  All Matrix ----------

pcs_matrix = np.zeros((total_users, total_users))
jac_matrix = np.zeros((total_users, total_users))
pcc_matrix = np.zeros((total_users, total_users))
msd_matrix = np.zeros((total_users, total_users))
cpcc_matrix = np.zeros((total_users, total_users))
spcc_matrix = np.zeros((total_users, total_users))
user_avg = np.zeros((total_users))
nhsm_matrix = np.zeros((total_users, total_users))


# -----------Find All Similarity Measure ----------- 

for i in range(0, total_users):
    for j in range(0,i):
        if i!=j:
               
            pcs_matrix[i][j] = cosine_similarity(i, j, dataset)
            pcs_matrix[j][i] = pcs_matrix[i][j] 
            y_pred=dataset[i]
            y_true=dataset[j]
            jac_matrix[i][j] = jaccard_repeats(y_pred,y_true)
            jac_matrix[j][i] = jac_matrix[i][j] 
            pcc_matrix[i][j] = pcc_repeats(y_pred,y_true)
            pcc_matrix[j][i] = pcc_matrix[i][j] 
            msd_matrix[i][j] = msd_repeats(y_pred,y_true)
            msd_matrix[j][i] = msd_matrix[i][j] 
            cpcc_matrix[i][j] = cpcc_repeats(y_pred,y_true)
            cpcc_matrix[j][i] = cpcc_matrix[i][j] 
            spcc_matrix[i][j] = spcc_cosine_similarity(y_pred,y_true)
            spcc_matrix[j][i] = spcc_matrix[i][j]
            nhsm_matrix[i][j] = nhsm_matrix_similarity(y_pred,y_true)
            nhsm_matrix[j][i] = nhsm_matrix[i][j]
    pcs_matrix[i][i] = 1
    spcc_matrix[i][i] = 1
    jac_matrix[i][i] = 1  
    pcc_matrix[i][i] = 1 
    msd_matrix[i][i] = 1 
    cpcc_matrix[i][i] = 1 
    user_avg[i] = user_mean(dataset[i])
    nhsm_matrix[i][i] = 1

print("cos=",pcs_matrix,'\n\n')
print("jac=",jac_matrix,'\n\n')
print("pcc=",pcc_matrix,'\n\n')
print("msd=",msd_matrix,'\n\n')
print("cpcc=",cpcc_matrix,'\n\n')
print("spcc=",spcc_matrix,'\n\n')
print("NHSM=",nhsm_matrix,'\n\n')



[['4', '3', '5', '4'], ['5', '3', '0', '0'], ['4', '3', '3', '4'], ['2', '1', '0', '0'], ['4', '2', '0', '0']]
['4', '3', '5', '4']
['5', '3', '0', '0']
['4', '3', '3', '4']
['2', '1', '0', '0']
['4', '2', '0', '0']
cos= [[1.         0.61219048 0.97483487 0.60553007 0.60553007]
 [0.61219048 1.         0.70335331 0.99705449 0.99705449]
 [0.97483487 0.70335331 1.         0.69570109 0.69570109]
 [0.60553007 0.99705449 0.69570109 1.         1.        ]
 [0.60553007 0.99705449 0.69570109 1.         1.        ]] 


jac= [[1.  0.5 1.  0.5 0.5]
 [0.5 1.  0.5 1.  1. ]
 [1.  0.5 1.  0.5 0.5]
 [0.5 1.  0.5 1.  1. ]
 [0.5 1.  0.5 1.  1. ]] 


pcc= [[1.         0.70710678 0.         0.70710678 0.70710678]
 [0.70710678 1.         1.         1.         1.        ]
 [0.         1.         1.         1.         1.        ]
 [0.70710678 1.         1.         1.         1.        ]
 [0.70710678 1.         1.         1.         1.        ]] 


msd= [[ 1.   0.5  0.  -3.   0.5]
 [ 0.5  1.   0.5 -5.5  0. ]
 